version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    target-branch: shio/20
    groups:
      all:
        patterns: [ "*" ]
    labels:
      - kind/dependency
    commit-message:
      prefix: shio
