<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>opencast-editor</artifactId>
  <packaging>bundle</packaging>
  <name>Opencast :: editor</name>
  <parent>
    <groupId>org.opencastproject</groupId>
    <artifactId>base</artifactId>
    <version>19-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <properties>
    <opencast.basedir>${project.basedir}/../..</opencast.basedir>
    <checkstyle.skip>false</checkstyle.skip>
    <nodejs.version>v20.10.0</nodejs.version>
  </properties>
  <profiles>
    <profile>
      <id>frontend-no-prebuilt</id>
      <properties>
        <ui.include.resource>/editor=-build/</ui.include.resource>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <configuration>
              <environmentVariables>
                <PUBLIC_URL>/editor-ui</PUBLIC_URL>
                <VITE_APP_SETTINGS_PATH>/ui/config/editor/editor-settings.toml</VITE_APP_SETTINGS_PATH>
              </environmentVariables>
            </configuration>
            <executions>
              <execution>
                <id>npm ci</id>
                <goals>
                  <goal>exec</goal>
                </goals>
                <phase>validate</phase>
                <configuration>
                  <executable>npm</executable>
                  <arguments>
                    <argument>ci</argument>
                  </arguments>
                </configuration>
              </execution>

              <execution>
                <id>npm run build</id>
                <goals>
                  <goal>exec</goal>
                </goals>
                <phase>generate-resources</phase>
                <configuration>
                  <executable>npm</executable>
                  <arguments>
                    <argument>run</argument>
                    <argument>build</argument>
                  </arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>buildnumber-maven-plugin</artifactId>
            <version>3.3.0</version>
            <executions>
              <execution>
                <phase>validate</phase>
                <goals>
                  <goal>create</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <doCheck>true</doCheck>
              <doUpdate>false</doUpdate>
              <failTheBuild>false</failTheBuild>
              <shortRevisionLength>7</shortRevisionLength>
              <buildNumberPropertyName>submoduleHash</buildNumberPropertyName>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>frontend</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <ui.include.resource>/editor=-build/</ui.include.resource>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <configuration>
              <nodeVersion>${nodejs.version}</nodeVersion>
              <installDirectory>target</installDirectory>
              <environmentVariables>
                <PUBLIC_URL>/editor-ui</PUBLIC_URL>
                <VITE_APP_SETTINGS_PATH>/ui/config/editor/editor-settings.toml</VITE_APP_SETTINGS_PATH>
              </environmentVariables>
            </configuration>
            <executions>
              <execution>
                <id>install node and npm</id>
                <phase>validate</phase>
                <goals>
                  <goal>install-node-and-npm</goal>
                </goals>
                <configuration>
                  <nodeVersion>${node.version}</nodeVersion>
                </configuration>
              </execution>
              <execution>
                <phase>validate</phase>
                <id>npm ci</id>
                <goals>
                  <goal>npm</goal>
                </goals>
                <configuration>
                  <arguments>ci</arguments>
                </configuration>
              </execution>
              <execution>
                <id>npm run build</id>
                <goals>
                  <goal>npm</goal>
                </goals>
                <phase>generate-resources</phase>
                <configuration>
                  <arguments>run build</arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-clean-plugin</artifactId>
            <configuration>
              <filesets>
                <fileset>
                  <directory>node_modules</directory>
                  <followSymlinks>false</followSymlinks>
                </fileset>
              </filesets>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>buildnumber-maven-plugin</artifactId>
            <version>3.3.0</version>
            <executions>
              <execution>
                <phase>validate</phase>
                <goals>
                  <goal>create</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <doCheck>true</doCheck>
              <doUpdate>false</doUpdate>
              <failTheBuild>false</failTheBuild>
              <shortRevisionLength>7</shortRevisionLength>
              <buildNumberPropertyName>submoduleHash</buildNumberPropertyName>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
            <!-- NOTE: This property is defined in the parent/main pom, at runtime.
                 Building this module directly will leave this blank and thus it will be omitted from the built jar.
                 Look up building specific maven project (-pl) if you need to build this module and care about this.
             -->
            <Build-Number>${buildNumber}</Build-Number>
            <Submodule-Hash>${submoduleHash}</Submodule-Hash>
            <!-- NOTE: This flag is showing if there are any un-committed modifications in the submodule.
                 It does *not* check to see if you have modified the submodule relative to the branch.
                 Adopters modifying their local forks should expect that this reads false.
                 Developers modifying their local copies for testing should expect this could read true.
            -->
            <Submodule-Tainted>${buildIsTainted}</Submodule-Tainted>
            <Include-Resource>${ui.include.resource}</Include-Resource>
            <!--<Private-Package>editor.*</Private-Package>-->
            <Http-Alias>/editor-ui</Http-Alias>
            <Http-Classpath>/editor</Http-Classpath>
            <Http-Welcome>index.html</Http-Welcome>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
